# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/xcl_design_debug_bridge_xsdbm_0.xci
# IP: The module: 'xcl_design_debug_bridge_xsdbm_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/bd_6ad6.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ad6 || ORIG_REF_NAME==bd_6ad6}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/ip/ip_0/bd_6ad6_xsdbm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ad6_xsdbm_0 || ORIG_REF_NAME==bd_6ad6_xsdbm_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/ip/ip_1/bd_6ad6_lut_buffer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ad6_lut_buffer_0 || ORIG_REF_NAME==bd_6ad6_lut_buffer_0}]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/bd_6ad6_ooc.xdc

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/xcl_design_debug_bridge_xsdbm_0.xci
# IP: The module: 'xcl_design_debug_bridge_xsdbm_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/bd_6ad6.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ad6 || ORIG_REF_NAME==bd_6ad6}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/ip/ip_0/bd_6ad6_xsdbm_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ad6_xsdbm_0 || ORIG_REF_NAME==bd_6ad6_xsdbm_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/ip/ip_1/bd_6ad6_lut_buffer_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ad6_lut_buffer_0 || ORIG_REF_NAME==bd_6ad6_lut_buffer_0}]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/bd_0/bd_6ad6_ooc.xdc
