# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/xcl_design.xdc

# Block Designs: bd/xcl_design/xcl_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design || ORIG_REF_NAME==xcl_design}]

# IP: bd/xcl_design/ip/xcl_design_axi_i2c_0/xcl_design_axi_i2c_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_axi_i2c_0 || ORIG_REF_NAME==xcl_design_axi_i2c_0}]

# IP: bd/xcl_design/ip/xcl_design_buf_refclk_bufg_0/xcl_design_buf_refclk_bufg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_buf_refclk_bufg_0 || ORIG_REF_NAME==xcl_design_buf_refclk_bufg_0}]

# IP: bd/xcl_design/ip/xcl_design_buf_refclk_ibuf_0/xcl_design_buf_refclk_ibuf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_buf_refclk_ibuf_0 || ORIG_REF_NAME==xcl_design_buf_refclk_ibuf_0}]

# IP: bd/xcl_design/ip/xcl_design_clkwiz_kernel_0/xcl_design_clkwiz_kernel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_clkwiz_kernel_0 || ORIG_REF_NAME==xcl_design_clkwiz_kernel_0}]

# IP: bd/xcl_design/ip/xcl_design_clkwiz_kernel2_0/xcl_design_clkwiz_kernel2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_clkwiz_kernel2_0 || ORIG_REF_NAME==xcl_design_clkwiz_kernel2_0}]

# IP: bd/xcl_design/ip/xcl_design_clkwiz_sysclks_0/xcl_design_clkwiz_sysclks_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_clkwiz_sysclks_0 || ORIG_REF_NAME==xcl_design_clkwiz_sysclks_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_ctrlclk_0/xcl_design_psreset_ctrlclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_ctrlclk_0 || ORIG_REF_NAME==xcl_design_psreset_ctrlclk_0}]

# IP: bd/xcl_design/ip/xcl_design_const_gnd_1_0/xcl_design_const_gnd_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_const_gnd_1_0 || ORIG_REF_NAME==xcl_design_const_gnd_1_0}]

# IP: bd/xcl_design/ip/xcl_design_const_gnd_3_0/xcl_design_const_gnd_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_const_gnd_3_0 || ORIG_REF_NAME==xcl_design_const_gnd_3_0}]

# IP: bd/xcl_design/ip/xcl_design_const_vcc_1_0/xcl_design_const_vcc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_const_vcc_1_0 || ORIG_REF_NAME==xcl_design_const_vcc_1_0}]

# IP: bd/xcl_design/ip/xcl_design_dma_pcie_0/xcl_design_dma_pcie_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_dma_pcie_0 || ORIG_REF_NAME==xcl_design_dma_pcie_0}]

# IP: bd/xcl_design/ip/xcl_design_const_featureid_high_0/xcl_design_const_featureid_high_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_const_featureid_high_0 || ORIG_REF_NAME==xcl_design_const_featureid_high_0}]

# IP: bd/xcl_design/ip/xcl_design_const_featureid_low_0/xcl_design_const_featureid_low_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_const_featureid_low_0 || ORIG_REF_NAME==xcl_design_const_featureid_low_0}]

# IP: bd/xcl_design/ip/xcl_design_gpio_featureid_0/xcl_design_gpio_featureid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_gpio_featureid_0 || ORIG_REF_NAME==xcl_design_gpio_featureid_0}]

# IP: bd/xcl_design/ip/xcl_design_ddr_calib_status_0/xcl_design_ddr_calib_status_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddr_calib_status_0 || ORIG_REF_NAME==xcl_design_ddr_calib_status_0}]

# IP: bd/xcl_design/ip/xcl_design_gate_pr_0/xcl_design_gate_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_gate_pr_0 || ORIG_REF_NAME==xcl_design_gate_pr_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_axilite_static_0/xcl_design_interconnect_axilite_static_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_axilite_static_0 || ORIG_REF_NAME==xcl_design_interconnect_axilite_static_0}]

# IP: bd/xcl_design/ip/xcl_design_xbar_0/xcl_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_xbar_0 || ORIG_REF_NAME==xcl_design_xbar_0}]

# IP: bd/xcl_design/ip/xcl_design_iob_static_0/xcl_design_iob_static_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_iob_static_0 || ORIG_REF_NAME==xcl_design_iob_static_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_regslice_ctrl_pr_0/xcl_design_psreset_regslice_ctrl_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_regslice_ctrl_pr_0 || ORIG_REF_NAME==xcl_design_psreset_regslice_ctrl_pr_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_regslice_data_pr_0/xcl_design_psreset_regslice_data_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_regslice_data_pr_0 || ORIG_REF_NAME==xcl_design_psreset_regslice_data_pr_0}]

# IP: bd/xcl_design/ip/xcl_design_regslice_control_0/xcl_design_regslice_control_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_regslice_control_0 || ORIG_REF_NAME==xcl_design_regslice_control_0}]

# IP: bd/xcl_design/ip/xcl_design_regslice_data_0/xcl_design_regslice_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_regslice_data_0 || ORIG_REF_NAME==xcl_design_regslice_data_0}]

# IP: bd/xcl_design/ip/xcl_design_slice_reset_kernel_pr_0/xcl_design_slice_reset_kernel_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_slice_reset_kernel_pr_0 || ORIG_REF_NAME==xcl_design_slice_reset_kernel_pr_0}]

# IP: bd/xcl_design/ip/xcl_design_slice_reset_system_pr_0/xcl_design_slice_reset_system_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_slice_reset_system_pr_0 || ORIG_REF_NAME==xcl_design_slice_reset_system_pr_0}]

# IP: bd/xcl_design/ip/xcl_design_startup_primitive_0/xcl_design_startup_primitive_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_startup_primitive_0 || ORIG_REF_NAME==xcl_design_startup_primitive_0}]

# IP: bd/xcl_design/ip/xcl_design_sys_mgmt_wiz_0/xcl_design_sys_mgmt_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_sys_mgmt_wiz_0 || ORIG_REF_NAME==xcl_design_sys_mgmt_wiz_0}]

# IP: bd/xcl_design/ip/xcl_design_regslice_apm_a_0/xcl_design_regslice_apm_a_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_regslice_apm_a_0 || ORIG_REF_NAME==xcl_design_regslice_apm_a_0}]

# IP: bd/xcl_design/ip/xcl_design_regslice_apm_b_0/xcl_design_regslice_apm_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_regslice_apm_b_0 || ORIG_REF_NAME==xcl_design_regslice_apm_b_0}]

# IP: bd/xcl_design/ip/xcl_design_regslice_fifo_a_0/xcl_design_regslice_fifo_a_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_regslice_fifo_a_0 || ORIG_REF_NAME==xcl_design_regslice_fifo_a_0}]

# IP: bd/xcl_design/ip/xcl_design_regslice_fifo_b_0/xcl_design_regslice_fifo_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_regslice_fifo_b_0 || ORIG_REF_NAME==xcl_design_regslice_fifo_b_0}]

# IP: bd/xcl_design/ip/xcl_design_xilmonitor_apm_0/xcl_design_xilmonitor_apm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_xilmonitor_apm_0 || ORIG_REF_NAME==xcl_design_xilmonitor_apm_0}]

# IP: bd/xcl_design/ip/xcl_design_xilmonitor_fifo0_0/xcl_design_xilmonitor_fifo0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_xilmonitor_fifo0_0 || ORIG_REF_NAME==xcl_design_xilmonitor_fifo0_0}]

# IP: bd/xcl_design/ip/xcl_design_xilmonitor_subset0_0/xcl_design_xilmonitor_subset0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_xilmonitor_subset0_0 || ORIG_REF_NAME==xcl_design_xilmonitor_subset0_0}]

# IP: bd/xcl_design/ip/xcl_design_logic_reset_op_0/xcl_design_logic_reset_op_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_logic_reset_op_0 || ORIG_REF_NAME==xcl_design_logic_reset_op_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_0/xcl_design_psreset_ddrmem_n_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_ddrmem_n_0 || ORIG_REF_NAME==xcl_design_psreset_ddrmem_n_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_ddrmem_n_2_0 || ORIG_REF_NAME==xcl_design_psreset_ddrmem_n_2_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_3_0/xcl_design_psreset_ddrmem_n_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_ddrmem_n_3_0 || ORIG_REF_NAME==xcl_design_psreset_ddrmem_n_3_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_4_0/xcl_design_psreset_ddrmem_n_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_ddrmem_n_4_0 || ORIG_REF_NAME==xcl_design_psreset_ddrmem_n_4_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_gate_pr_apmclk_0/xcl_design_psreset_gate_pr_apmclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_gate_pr_apmclk_0 || ORIG_REF_NAME==xcl_design_psreset_gate_pr_apmclk_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_gate_pr_control_0/xcl_design_psreset_gate_pr_control_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_gate_pr_control_0 || ORIG_REF_NAME==xcl_design_psreset_gate_pr_control_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_gate_pr_data_0/xcl_design_psreset_gate_pr_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_gate_pr_data_0 || ORIG_REF_NAME==xcl_design_psreset_gate_pr_data_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_gate_pr_kernel_0 || ORIG_REF_NAME==xcl_design_psreset_gate_pr_kernel_0}]

# IP: bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel2_0/xcl_design_psreset_gate_pr_kernel2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_psreset_gate_pr_kernel2_0 || ORIG_REF_NAME==xcl_design_psreset_gate_pr_kernel2_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_aximm_ddrmem0_0/xcl_design_interconnect_aximm_ddrmem0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_aximm_ddrmem0_0 || ORIG_REF_NAME==xcl_design_interconnect_aximm_ddrmem0_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_aximm_ddrmem1_0/xcl_design_interconnect_aximm_ddrmem1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_aximm_ddrmem1_0 || ORIG_REF_NAME==xcl_design_interconnect_aximm_ddrmem1_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_aximm_ddrmem2_0/xcl_design_interconnect_aximm_ddrmem2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_aximm_ddrmem2_0 || ORIG_REF_NAME==xcl_design_interconnect_aximm_ddrmem2_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_aximm_ddrmem3_0/xcl_design_interconnect_aximm_ddrmem3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_aximm_ddrmem3_0 || ORIG_REF_NAME==xcl_design_interconnect_aximm_ddrmem3_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_aximm_host_0/xcl_design_interconnect_aximm_host_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_aximm_host_0 || ORIG_REF_NAME==xcl_design_interconnect_aximm_host_0}]

# IP: bd/xcl_design/ip/xcl_design_interconnect_axilite_0/xcl_design_interconnect_axilite_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_interconnect_axilite_0 || ORIG_REF_NAME==xcl_design_interconnect_axilite_0}]

# IP: bd/xcl_design/ip/xcl_design_xbar_1/xcl_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_xbar_1 || ORIG_REF_NAME==xcl_design_xbar_1}]

# IP: bd/xcl_design/ip/xcl_design_axicc_ddrmem_2_ctrl_0/xcl_design_axicc_ddrmem_2_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_axicc_ddrmem_2_ctrl_0 || ORIG_REF_NAME==xcl_design_axicc_ddrmem_2_ctrl_0}]

# IP: bd/xcl_design/ip/xcl_design_axicc_ddrmem_3_ctrl_0/xcl_design_axicc_ddrmem_3_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_axicc_ddrmem_3_ctrl_0 || ORIG_REF_NAME==xcl_design_axicc_ddrmem_3_ctrl_0}]

# IP: bd/xcl_design/ip/xcl_design_concat_ddrcalib_0/xcl_design_concat_ddrcalib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_concat_ddrcalib_0 || ORIG_REF_NAME==xcl_design_concat_ddrcalib_0}]

# IP: bd/xcl_design/ip/xcl_design_ddrmem_0_0/xcl_design_ddrmem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_0 || ORIG_REF_NAME==xcl_design_ddrmem_0_0}]

# IP: bd/xcl_design/ip/xcl_design_ddrmem_1_0/xcl_design_ddrmem_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_1_0 || ORIG_REF_NAME==xcl_design_ddrmem_1_0}]

# IP: bd/xcl_design/ip/xcl_design_ddrmem_2_0/xcl_design_ddrmem_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_2_0 || ORIG_REF_NAME==xcl_design_ddrmem_2_0}]

# IP: bd/xcl_design/ip/xcl_design_ddrmem_3_0/xcl_design_ddrmem_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0 || ORIG_REF_NAME==xcl_design_ddrmem_3_0}]

# IP: bd/xcl_design/ip/xcl_design_logic_ddrcalib_op_0/xcl_design_logic_ddrcalib_op_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_logic_ddrcalib_op_0 || ORIG_REF_NAME==xcl_design_logic_ddrcalib_op_0}]

# IP: bd/xcl_design/ip/xcl_design_concat_flash_dq_o_0/xcl_design_concat_flash_dq_o_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_concat_flash_dq_o_0 || ORIG_REF_NAME==xcl_design_concat_flash_dq_o_0}]

# IP: bd/xcl_design/ip/xcl_design_concat_flash_tri_0/xcl_design_concat_flash_tri_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_concat_flash_tri_0 || ORIG_REF_NAME==xcl_design_concat_flash_tri_0}]

# IP: bd/xcl_design/ip/xcl_design_debug_bridge_xsdbm_0/xcl_design_debug_bridge_xsdbm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_debug_bridge_xsdbm_0 || ORIG_REF_NAME==xcl_design_debug_bridge_xsdbm_0}]

# IP: bd/xcl_design/ip/xcl_design_flash_programmer_0/xcl_design_flash_programmer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_flash_programmer_0 || ORIG_REF_NAME==xcl_design_flash_programmer_0}]

# IP: bd/xcl_design/ip/xcl_design_slice_ss_0_0/xcl_design_slice_ss_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_slice_ss_0_0 || ORIG_REF_NAME==xcl_design_slice_ss_0_0}]

# IP: bd/xcl_design/ip/xcl_design_slice_ss_1_0/xcl_design_slice_ss_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_slice_ss_1_0 || ORIG_REF_NAME==xcl_design_slice_ss_1_0}]

# IP: bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_u_ocl_region_0 || ORIG_REF_NAME==xcl_design_u_ocl_region_0}]

# IP: bd/xcl_design/ip/xcl_design_s00_regslice_0/xcl_design_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_s00_regslice_0 || ORIG_REF_NAME==xcl_design_s00_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_s00_regslice_1/xcl_design_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_s00_regslice_1 || ORIG_REF_NAME==xcl_design_s00_regslice_1}]

# IP: bd/xcl_design/ip/xcl_design_m00_regslice_0/xcl_design_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m00_regslice_0 || ORIG_REF_NAME==xcl_design_m00_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_m01_regslice_0/xcl_design_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m01_regslice_0 || ORIG_REF_NAME==xcl_design_m01_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_m02_regslice_0/xcl_design_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m02_regslice_0 || ORIG_REF_NAME==xcl_design_m02_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_m03_regslice_0/xcl_design_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m03_regslice_0 || ORIG_REF_NAME==xcl_design_m03_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_m04_regslice_0/xcl_design_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m04_regslice_0 || ORIG_REF_NAME==xcl_design_m04_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_m05_regslice_0/xcl_design_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m05_regslice_0 || ORIG_REF_NAME==xcl_design_m05_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_m06_regslice_0/xcl_design_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_m06_regslice_0 || ORIG_REF_NAME==xcl_design_m06_regslice_0}]

# IP: bd/xcl_design/ip/xcl_design_auto_cc_0/xcl_design_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_auto_cc_0 || ORIG_REF_NAME==xcl_design_auto_cc_0}]

# IP: bd/xcl_design/ip/xcl_design_auto_cc_1/xcl_design_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_auto_cc_1 || ORIG_REF_NAME==xcl_design_auto_cc_1}]

# IP: bd/xcl_design/ip/xcl_design_auto_cc_2/xcl_design_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_auto_cc_2 || ORIG_REF_NAME==xcl_design_auto_cc_2}]

# XDC: bd/xcl_design/xcl_design_ooc.xdc
