set_property SRC_FILE_INFO {cfile:C:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/constrs_1/imports/constraints/xcl_design.xdc rfile:../../../xcl_design.srcs/constrs_1/imports/constraints/xcl_design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property HIGH_PRIORITY true [get_nets xcl_design_i/base_region/base_clocking/clkwiz_sysclks/inst/clk_out1]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property HIGH_PRIORITY true [get_nets xcl_design_i/expanded_region/memc/ddrmem_0/inst/u_ddr4_infrastructure/div_clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property HIGH_PRIORITY true [get_nets xcl_design_i/expanded_region/memc/ddrmem_1/inst/u_ddr4_infrastructure/c0_ddr4_ui_clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property HIGH_PRIORITY true [get_nets xcl_design_i/expanded_region/memc/ddrmem_2/inst/u_ddr4_infrastructure/div_clk]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property HIGH_PRIORITY true [get_nets xcl_design_i/expanded_region/memc/ddrmem_3/inst/u_ddr4_infrastructure/div_clk]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property HIGH_PRIORITY true [get_nets xcl_design_i/base_region/dma_pcie/inst/pcie3_ip_i/inst/gt_top_i/phy_clk_i/CLK_USERCLK]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT11    [get_ports {ref_clk_clk_p[0]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR26    [get_ports perst_n]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY25    [get_ports init_calib_complete]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW25    [get_ports led_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL27    [get_ports emc_clk]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26    [get_ports spi_1_io0_io]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26    [get_ports spi_1_io1_io]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL25    [get_ports spi_1_io2_io]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM25    [get_ports spi_1_io3_io]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF27    [get_ports spi_1_ss_io]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN24    [get_ports iic_scl_io]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP24    [get_ports iic_sda_io]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL24    [get_ports iic_reset_n]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_3_1_X0Y0           [get_cells xcl_design_i/base_region/dma_pcie/inst/pcie3_ip_i/inst/pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/PCIE_3_1_inst]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC CONFIG_SITE_X0Y0        [get_cells -hier {*STARTUP*_inst}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_REGION X4Y1           [get_cells xcl_design_i/base_region/pr_isolation_expanded/iob_static/inst/emc_clk_bufg]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets xcl_design_i/base_region/pr_isolation_expanded/iob_static/inst/emc_clk_ibuf/O]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_expanded_region
add_cells_to_pblock [get_pblocks pblock_expanded_region] [get_cells -quiet [list xcl_design_i/expanded_region]]
resize_pblock [get_pblocks pblock_expanded_region] -add {SLICE_X0Y300:SLICE_X142Y599 SLICE_X0Y180:SLICE_X133Y299 SLICE_X0Y120:SLICE_X122Y179 SLICE_X97Y60:SLICE_X122Y119 SLICE_X0Y0:SLICE_X95Y119 SLICE_X97Y30:SLICE_X118Y59 SLICE_X97Y0:SLICE_X117Y29}
resize_pblock [get_pblocks pblock_expanded_region] -add {BITSLICE_CONTROL_X0Y8:BITSLICE_CONTROL_X1Y15}
resize_pblock [get_pblocks pblock_expanded_region] -add {BITSLICE_RX_TX_X0Y52:BITSLICE_RX_TX_X1Y103}
resize_pblock [get_pblocks pblock_expanded_region] -add {BITSLICE_TX_X0Y8:BITSLICE_TX_X1Y15}
resize_pblock [get_pblocks pblock_expanded_region] -add {DSP48E2_X22Y12:DSP48E2_X22Y239 DSP48E2_X0Y0:DSP48E2_X21Y239}
resize_pblock [get_pblocks pblock_expanded_region] -add {GTHE3_CHANNEL_X1Y20:GTHE3_CHANNEL_X1Y39 GTHE3_CHANNEL_X0Y8:GTHE3_CHANNEL_X0Y39}
resize_pblock [get_pblocks pblock_expanded_region] -add {GTHE3_COMMON_X1Y5:GTHE3_COMMON_X1Y9 GTHE3_COMMON_X0Y2:GTHE3_COMMON_X0Y9}
resize_pblock [get_pblocks pblock_expanded_region] -add {IOB_X2Y104:IOB_X2Y519 IOB_X0Y0:IOB_X1Y519}
resize_pblock [get_pblocks pblock_expanded_region] -add {LAGUNA_X22Y240:LAGUNA_X23Y479 LAGUNA_X20Y120:LAGUNA_X21Y479 LAGUNA_X0Y0:LAGUNA_X19Y479}
resize_pblock [get_pblocks pblock_expanded_region] -add {MMCME3_ADV_X0Y1:MMCME3_ADV_X1Y1}
resize_pblock [get_pblocks pblock_expanded_region] -add {PCIE_3_1_X0Y1:PCIE_3_1_X0Y5}
resize_pblock [get_pblocks pblock_expanded_region] -add {PLLE3_ADV_X0Y2:PLLE3_ADV_X1Y3}
resize_pblock [get_pblocks pblock_expanded_region] -add {PLL_SELECT_SITE_X0Y8:PLL_SELECT_SITE_X1Y15}
resize_pblock [get_pblocks pblock_expanded_region] -add {RAMB18_X15Y72:RAMB18_X17Y239 RAMB18_X0Y0:RAMB18_X14Y239}
resize_pblock [get_pblocks pblock_expanded_region] -add {RAMB36_X15Y36:RAMB36_X17Y119 RAMB36_X0Y0:RAMB36_X14Y119}
resize_pblock [get_pblocks pblock_expanded_region] -add {RIU_OR_X1Y4:RIU_OR_X1Y7 RIU_OR_X0Y0:RIU_OR_X0Y7}
resize_pblock [get_pblocks pblock_expanded_region] -add {SYSMONE1_X0Y1:SYSMONE1_X0Y1}
resize_pblock [get_pblocks pblock_expanded_region] -add {XIPHY_FEEDTHROUGH_X0Y1:XIPHY_FEEDTHROUGH_X7Y1}
set_property CONTAIN_ROUTING 1 [get_pblocks pblock_expanded_region]
set_property EXCLUDE_PLACEMENT 1 [get_pblocks pblock_expanded_region]
set_property SNAPPING_MODE ON [get_pblocks pblock_expanded_region]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_lower
add_cells_to_pblock [get_pblocks pblock_lower] [get_cells -quiet [list xcl_design_i/expanded_region/interconnect/interconnect_aximm_host xcl_design_i/expanded_region/interconnect_axilite xcl_design_i/expanded_region/u_ocl_region]]
resize_pblock [get_pblocks pblock_lower] -add {SLICE_X123Y180:SLICE_X133Y299 SLICE_X119Y60:SLICE_X122Y299 SLICE_X118Y30:SLICE_X118Y119 SLICE_X97Y0:SLICE_X117Y119}
resize_pblock [get_pblocks pblock_lower] -add {DSP48E2_X18Y12:DSP48E2_X22Y47 DSP48E2_X18Y0:DSP48E2_X21Y11}
resize_pblock [get_pblocks pblock_lower] -add {LAGUNA_X16Y0:LAGUNA_X19Y119}
resize_pblock [get_pblocks pblock_lower] -add {RAMB18_X15Y72:RAMB18_X17Y119 RAMB18_X12Y0:RAMB18_X14Y47}
resize_pblock [get_pblocks pblock_lower] -add {RAMB36_X15Y36:RAMB36_X17Y59 RAMB36_X12Y0:RAMB36_X14Y23}
resize_pblock [get_pblocks pblock_lower] -add {CLOCKREGION_X0Y2:CLOCKREGION_X4Y4 CLOCKREGION_X0Y0:CLOCKREGION_X3Y1}
set_property SNAPPING_MODE ON [get_pblocks pblock_lower]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_upper
add_cells_to_pblock [get_pblocks pblock_upper] [get_cells -quiet [list xcl_design_i/expanded_region/memc/axicc_ddrmem_2_ctrl xcl_design_i/expanded_region/memc/axicc_ddrmem_3_ctrl]]
resize_pblock [get_pblocks pblock_upper] -add {SLICE_X119Y300:SLICE_X142Y599}
resize_pblock [get_pblocks pblock_upper] -add {RAMB18_X15Y120:RAMB18_X17Y239}
resize_pblock [get_pblocks pblock_upper] -add {RAMB36_X15Y60:RAMB36_X17Y119}
resize_pblock [get_pblocks pblock_upper] -add {CLOCKREGION_X0Y5:CLOCKREGION_X4Y9}
set_property SNAPPING_MODE ON [get_pblocks pblock_upper]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_apm
add_cells_to_pblock [get_pblocks pblock_apm] [get_cells -quiet [list xcl_design_i/expanded_region/apm_sys/xilmonitor_fifo0 xcl_design_i/expanded_region/apm_sys/xilmonitor_subset0]]
resize_pblock [get_pblocks pblock_apm] -add {CLOCKREGION_X3Y0:CLOCKREGION_X3Y1}
set_property SNAPPING_MODE ON [get_pblocks pblock_apm]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
add_cells_to_pblock [get_pblocks pblock_apm] [get_cells [list xcl_design_i/expanded_region/apm_sys/xilmonitor_apm/inst/GEN_PROFILE_Trace_Mode.profile_trace_mode_inst]]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ddrmem_0
add_cells_to_pblock [get_pblocks pblock_ddrmem_0] [get_cells -quiet [list xcl_design_i/expanded_region/memc/ddrmem_0]]
resize_pblock [get_pblocks pblock_ddrmem_0] -add {CLOCKREGION_X2Y0:CLOCKREGION_X2Y3}
set_property SNAPPING_MODE ON [get_pblocks pblock_ddrmem_0]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ddrmem_1
add_cells_to_pblock [get_pblocks pblock_ddrmem_1] [get_cells -quiet [list xcl_design_i/expanded_region/memc/ddrmem_1]]
resize_pblock [get_pblocks pblock_ddrmem_1] -add {CLOCKREGION_X4Y2:CLOCKREGION_X4Y4}
set_property SNAPPING_MODE ON [get_pblocks pblock_ddrmem_1]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ddrmem_2
add_cells_to_pblock [get_pblocks pblock_ddrmem_2] [get_cells -quiet [list xcl_design_i/expanded_region/memc/ddrmem_2]]
resize_pblock [get_pblocks pblock_ddrmem_2] -add {CLOCKREGION_X2Y6:CLOCKREGION_X2Y9}
set_property SNAPPING_MODE ON [get_pblocks pblock_ddrmem_2]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ddrmem_3
add_cells_to_pblock [get_pblocks pblock_ddrmem_3] [get_cells -quiet [list xcl_design_i/expanded_region/memc/ddrmem_3]]
resize_pblock [get_pblocks pblock_ddrmem_3] -add {CLOCKREGION_X4Y6:CLOCKREGION_X4Y9}
set_property SNAPPING_MODE ON [get_pblocks pblock_ddrmem_3]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA34       [get_ports c1_sys_clk_p]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB34       [get_ports c1_sys_clk_n]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW14       [get_ports c0_sys_clk_p]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW13       [get_ports c0_sys_clk_n]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C36        [get_ports c2_sys_clk_p]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C37        [get_ports c2_sys_clk_n]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19        [get_ports c3_sys_clk_p]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18        [get_ports c3_sys_clk_n]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13       [get_ports c0_ddr4_act_n]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM14       [get_ports {c0_ddr4_adr[0]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM15       [get_ports {c0_ddr4_adr[10]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR13       [get_ports {c0_ddr4_adr[11]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR16       [get_ports {c0_ddr4_adr[12]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13       [get_ports {c0_ddr4_adr[13]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL14       [get_ports {c0_ddr4_adr[14]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN14       [get_ports {c0_ddr4_adr[15]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP13       [get_ports {c0_ddr4_adr[16]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV16       [get_ports {c0_ddr4_adr[1]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT13       [get_ports {c0_ddr4_adr[2]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP14       [get_ports {c0_ddr4_adr[3]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU16       [get_ports {c0_ddr4_adr[4]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU15       [get_ports {c0_ddr4_adr[5]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15       [get_ports {c0_ddr4_adr[6]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR15       [get_ports {c0_ddr4_adr[7]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15       [get_ports {c0_ddr4_adr[8]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP15       [get_ports {c0_ddr4_adr[9]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW16       [get_ports {c0_ddr4_ba[0]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15       [get_ports {c0_ddr4_ba[1]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13       [get_ports {c0_ddr4_bg[0]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14       [get_ports {c0_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV14       [get_ports {c0_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB16       [get_ports {c0_ddr4_cke[0]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF13       [get_ports {c0_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE17       [get_ports {c0_ddr4_dm_n[0]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY17       [get_ports {c0_ddr4_dm_n[1]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT19       [get_ports {c0_ddr4_dm_n[2]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN18       [get_ports {c0_ddr4_dm_n[3]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF14       [get_ports {c0_ddr4_dm_n[4]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA12       [get_ports {c0_ddr4_dm_n[5]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE7        [get_ports {c0_ddr4_dm_n[6]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC12       [get_ports {c0_ddr4_dm_n[7]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF18       [get_ports {c0_ddr4_dq[0]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW20       [get_ports {c0_ddr4_dq[10]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV18       [get_ports {c0_ddr4_dq[11]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW18       [get_ports {c0_ddr4_dq[12]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA18       [get_ports {c0_ddr4_dq[13]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV19       [get_ports {c0_ddr4_dq[14]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY18       [get_ports {c0_ddr4_dq[15]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP18       [get_ports {c0_ddr4_dq[16]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR20       [get_ports {c0_ddr4_dq[17]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT20       [get_ports {c0_ddr4_dq[18]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT18       [get_ports {c0_ddr4_dq[19]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE18       [get_ports {c0_ddr4_dq[1]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20       [get_ports {c0_ddr4_dq[20]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR18       [get_ports {c0_ddr4_dq[21]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU20       [get_ports {c0_ddr4_dq[22]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU17       [get_ports {c0_ddr4_dq[23]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM16       [get_ports {c0_ddr4_dq[24]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP19       [get_ports {c0_ddr4_dq[25]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN16       [get_ports {c0_ddr4_dq[26]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN19       [get_ports {c0_ddr4_dq[27]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19       [get_ports {c0_ddr4_dq[28]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL20       [get_ports {c0_ddr4_dq[29]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF19       [get_ports {c0_ddr4_dq[2]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL19       [get_ports {c0_ddr4_dq[30]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20       [get_ports {c0_ddr4_dq[31]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF15       [get_ports {c0_ddr4_dq[32]}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC14       [get_ports {c0_ddr4_dq[33]}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD16       [get_ports {c0_ddr4_dq[34]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD14       [get_ports {c0_ddr4_dq[35]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE15       [get_ports {c0_ddr4_dq[36]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD15       [get_ports {c0_ddr4_dq[37]}]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC13       [get_ports {c0_ddr4_dq[38]}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE16       [get_ports {c0_ddr4_dq[39]}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC17       [get_ports {c0_ddr4_dq[3]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY12       [get_ports {c0_ddr4_dq[40]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY11       [get_ports {c0_ddr4_dq[41]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA13       [get_ports {c0_ddr4_dq[42]}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY15       [get_ports {c0_ddr4_dq[43]}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA15       [get_ports {c0_ddr4_dq[44]}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA14       [get_ports {c0_ddr4_dq[45]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY16       [get_ports {c0_ddr4_dq[46]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY13       [get_ports {c0_ddr4_dq[47]}]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE12       [get_ports {c0_ddr4_dq[48]}]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF9        [get_ports {c0_ddr4_dq[49]}]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC18       [get_ports {c0_ddr4_dq[4]}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD8        [get_ports {c0_ddr4_dq[50]}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD9        [get_ports {c0_ddr4_dq[51]}]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF12       [get_ports {c0_ddr4_dq[52]}]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF10       [get_ports {c0_ddr4_dq[53]}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE8        [get_ports {c0_ddr4_dq[54]}]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF8        [get_ports {c0_ddr4_dq[55]}]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA9        [get_ports {c0_ddr4_dq[56]}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB9        [get_ports {c0_ddr4_dq[57]}]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC9        [get_ports {c0_ddr4_dq[58]}]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB11       [get_ports {c0_ddr4_dq[59]}]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB17       [get_ports {c0_ddr4_dq[5]}]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC8        [get_ports {c0_ddr4_dq[60]}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC7        [get_ports {c0_ddr4_dq[61]}]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB10       [get_ports {c0_ddr4_dq[62]}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA8        [get_ports {c0_ddr4_dq[63]}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD18       [get_ports {c0_ddr4_dq[6]}]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB19       [get_ports {c0_ddr4_dq[7]}]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY20       [get_ports {c0_ddr4_dq[8]}]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW19       [get_ports {c0_ddr4_dq[9]}]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC19       [get_ports {c0_ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD19       [get_ports {c0_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV21       [get_ports {c0_ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW21       [get_ports {c0_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR17       [get_ports {c0_ddr4_dqs_t[2]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT17       [get_ports {c0_ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL17       [get_ports {c0_ddr4_dqs_t[3]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM17       [get_ports {c0_ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD13       [get_ports {c0_ddr4_dqs_t[4]}]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE13       [get_ports {c0_ddr4_dqs_c[4]}]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB15       [get_ports {c0_ddr4_dqs_t[5]}]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB14       [get_ports {c0_ddr4_dqs_c[5]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE11       [get_ports {c0_ddr4_dqs_t[6]}]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE10       [get_ports {c0_ddr4_dqs_c[6]}]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA7        [get_ports {c0_ddr4_dqs_t[7]}]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB7        [get_ports {c0_ddr4_dqs_c[7]}]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB12       [get_ports {c0_ddr4_odt[0]}]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU19       [get_ports c0_ddr4_reset_n]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA33       [get_ports c1_ddr4_act_n]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM34       [get_ports {c1_ddr4_adr[0]}]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM32       [get_ports {c1_ddr4_adr[10]}]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN33       [get_ports {c1_ddr4_adr[11]}]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT33       [get_ports {c1_ddr4_adr[12]}]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP34       [get_ports {c1_ddr4_adr[13]}]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL34       [get_ports {c1_ddr4_adr[14]}]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN34       [get_ports {c1_ddr4_adr[15]}]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN32       [get_ports {c1_ddr4_adr[16]}]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW33       [get_ports {c1_ddr4_adr[1]}]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL33       [get_ports {c1_ddr4_adr[2]}]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR33       [get_ports {c1_ddr4_adr[3]}]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV33       [get_ports {c1_ddr4_adr[4]}]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW34       [get_ports {c1_ddr4_adr[5]}]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV34       [get_ports {c1_ddr4_adr[6]}]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT34       [get_ports {c1_ddr4_adr[7]}]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL32       [get_ports {c1_ddr4_adr[8]}]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP33       [get_ports {c1_ddr4_adr[9]}]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY35       [get_ports {c1_ddr4_ba[0]}]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY36       [get_ports {c1_ddr4_ba[1]}]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY33       [get_ports {c1_ddr4_bg[0]}]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW35       [get_ports {c1_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW36       [get_ports {c1_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF35       [get_ports {c1_ddr4_cke[0]}]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB38       [get_ports {c1_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF32       [get_ports {c1_ddr4_dm_n[0]}]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC31       [get_ports {c1_ddr4_dm_n[1]}]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW29       [get_ports {c1_ddr4_dm_n[2]}]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP31       [get_ports {c1_ddr4_dm_n[3]}]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ27       [get_ports {c1_ddr4_dm_n[4]}]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH34       [get_ports {c1_ddr4_dm_n[5]}]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE31       [get_ports {c1_ddr4_dm_n[6]}]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA32       [get_ports {c1_ddr4_dm_n[7]}]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC34       [get_ports {c1_ddr4_dm_n[8]}]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE32       [get_ports {c1_ddr4_dq[0]}]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA29       [get_ports {c1_ddr4_dq[10]}]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY30       [get_ports {c1_ddr4_dq[11]}]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA30       [get_ports {c1_ddr4_dq[12]}]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB31       [get_ports {c1_ddr4_dq[13]}]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY31       [get_ports {c1_ddr4_dq[14]}]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB30       [get_ports {c1_ddr4_dq[15]}]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU30       [get_ports {c1_ddr4_dq[16]}]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT30       [get_ports {c1_ddr4_dq[17]}]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV31       [get_ports {c1_ddr4_dq[18]}]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU32       [get_ports {c1_ddr4_dq[19]}]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF30       [get_ports {c1_ddr4_dq[1]}]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT29       [get_ports {c1_ddr4_dq[20]}]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU31       [get_ports {c1_ddr4_dq[21]}]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW31       [get_ports {c1_ddr4_dq[22]}]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV32       [get_ports {c1_ddr4_dq[23]}]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN29       [get_ports {c1_ddr4_dq[24]}]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR30       [get_ports {c1_ddr4_dq[25]}]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP29       [get_ports {c1_ddr4_dq[26]}]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP30       [get_ports {c1_ddr4_dq[27]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN31       [get_ports {c1_ddr4_dq[28]}]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL29       [get_ports {c1_ddr4_dq[29]}]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE31       [get_ports {c1_ddr4_dq[2]}]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM31       [get_ports {c1_ddr4_dq[30]}]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL30       [get_ports {c1_ddr4_dq[31]}]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK28       [get_ports {c1_ddr4_dq[32]}]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ31       [get_ports {c1_ddr4_dq[33]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ29       [get_ports {c1_ddr4_dq[34]}]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG30       [get_ports {c1_ddr4_dq[35]}]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ28       [get_ports {c1_ddr4_dq[36]}]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG29       [get_ports {c1_ddr4_dq[37]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK31       [get_ports {c1_ddr4_dq[38]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ30       [get_ports {c1_ddr4_dq[39]}]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE33       [get_ports {c1_ddr4_dq[3]}]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH33       [get_ports {c1_ddr4_dq[40]}]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ33       [get_ports {c1_ddr4_dq[41]}]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF33       [get_ports {c1_ddr4_dq[42]}]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG34       [get_ports {c1_ddr4_dq[43]}]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG31       [get_ports {c1_ddr4_dq[44]}]
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG32       [get_ports {c1_ddr4_dq[45]}]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF34       [get_ports {c1_ddr4_dq[46]}]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF32       [get_ports {c1_ddr4_dq[47]}]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC32       [get_ports {c1_ddr4_dq[48]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF30       [get_ports {c1_ddr4_dq[49]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD29       [get_ports {c1_ddr4_dq[4]}]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD34       [get_ports {c1_ddr4_dq[50]}]
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC34       [get_ports {c1_ddr4_dq[51]}]
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC33       [get_ports {c1_ddr4_dq[52]}]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE30       [get_ports {c1_ddr4_dq[53]}]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD33       [get_ports {c1_ddr4_dq[54]}]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE33       [get_ports {c1_ddr4_dq[55]}]
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W33        [get_ports {c1_ddr4_dq[56]}]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y32        [get_ports {c1_ddr4_dq[57]}]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y33        [get_ports {c1_ddr4_dq[58]}]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA34       [get_ports {c1_ddr4_dq[59]}]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD33       [get_ports {c1_ddr4_dq[5]}]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W30        [get_ports {c1_ddr4_dq[60]}]
set_property src_info {type:XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y30        [get_ports {c1_ddr4_dq[61]}]
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB34       [get_ports {c1_ddr4_dq[62]}]
set_property src_info {type:XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W34        [get_ports {c1_ddr4_dq[63]}]
set_property src_info {type:XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA35       [get_ports {c1_ddr4_dq[64]}]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB35       [get_ports {c1_ddr4_dq[65]}]
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB36       [get_ports {c1_ddr4_dq[66]}]
set_property src_info {type:XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC36       [get_ports {c1_ddr4_dq[67]}]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD36       [get_ports {c1_ddr4_dq[68]}]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE36       [get_ports {c1_ddr4_dq[69]}]
set_property src_info {type:XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE30       [get_ports {c1_ddr4_dq[6]}]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD35       [get_ports {c1_ddr4_dq[70]}]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE35       [get_ports {c1_ddr4_dq[71]}]
set_property src_info {type:XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC29       [get_ports {c1_ddr4_dq[7]}]
set_property src_info {type:XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB29       [get_ports {c1_ddr4_dq[8]}]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY32       [get_ports {c1_ddr4_dq[9]}]
set_property src_info {type:XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD30       [get_ports {c1_ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD31       [get_ports {c1_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA32       [get_ports {c1_ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:1 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB32       [get_ports {c1_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU29       [get_ports {c1_ddr4_dqs_t[2]}]
set_property src_info {type:XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV29       [get_ports {c1_ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM29       [get_ports {c1_ddr4_dqs_t[3]}]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM30       [get_ports {c1_ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH28       [get_ports {c1_ddr4_dqs_t[4]}]
set_property src_info {type:XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH29       [get_ports {c1_ddr4_dqs_c[4]}]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH31       [get_ports {c1_ddr4_dqs_t[5]}]
set_property src_info {type:XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH32       [get_ports {c1_ddr4_dqs_c[5]}]
set_property src_info {type:XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC31       [get_ports {c1_ddr4_dqs_t[6]}]
set_property src_info {type:XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD31       [get_ports {c1_ddr4_dqs_c[6]}]
set_property src_info {type:XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W31        [get_ports {c1_ddr4_dqs_t[7]}]
set_property src_info {type:XDC file:1 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y31        [get_ports {c1_ddr4_dqs_c[7]}]
set_property src_info {type:XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB37       [get_ports {c1_ddr4_dqs_t[8]}]
set_property src_info {type:XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC37       [get_ports {c1_ddr4_dqs_c[8]}]
set_property src_info {type:XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD34       [get_ports {c1_ddr4_odt[0]}]
set_property src_info {type:XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ34       [get_ports c1_ddr4_reset_n]
set_property src_info {type:XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A38        [get_ports c2_ddr4_act_n]
set_property src_info {type:XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C31        [get_ports {c2_ddr4_adr[0]}]
set_property src_info {type:XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B32        [get_ports {c2_ddr4_adr[10]}]
set_property src_info {type:XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A33        [get_ports {c2_ddr4_adr[11]}]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B34        [get_ports {c2_ddr4_adr[12]}]
set_property src_info {type:XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C33        [get_ports {c2_ddr4_adr[13]}]
set_property src_info {type:XDC file:1 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D31        [get_ports {c2_ddr4_adr[14]}]
set_property src_info {type:XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D33        [get_ports {c2_ddr4_adr[15]}]
set_property src_info {type:XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A32        [get_ports {c2_ddr4_adr[16]}]
set_property src_info {type:XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D35        [get_ports {c2_ddr4_adr[1]}]
set_property src_info {type:XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B31        [get_ports {c2_ddr4_adr[2]}]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C34        [get_ports {c2_ddr4_adr[3]}]
set_property src_info {type:XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E35        [get_ports {c2_ddr4_adr[4]}]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A35        [get_ports {c2_ddr4_adr[5]}]
set_property src_info {type:XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B35        [get_ports {c2_ddr4_adr[6]}]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A34        [get_ports {c2_ddr4_adr[7]}]
set_property src_info {type:XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C32        [get_ports {c2_ddr4_adr[8]}]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D34        [get_ports {c2_ddr4_adr[9]}]
set_property src_info {type:XDC file:1 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E36        [get_ports {c2_ddr4_ba[0]}]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D36        [get_ports {c2_ddr4_ba[1]}]
set_property src_info {type:XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A37        [get_ports {c2_ddr4_bg[0]}]
set_property src_info {type:XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B36        [get_ports {c2_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B37        [get_ports {c2_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F38        [get_ports {c2_ddr4_cke[0]}]
set_property src_info {type:XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F34        [get_ports {c2_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U34        [get_ports {c2_ddr4_dm_n[0]}]
set_property src_info {type:XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R30        [get_ports {c2_ddr4_dm_n[1]}]
set_property src_info {type:XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M31        [get_ports {c2_ddr4_dm_n[2]}]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G30        [get_ports {c2_ddr4_dm_n[3]}]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T28        [get_ports {c2_ddr4_dm_n[4]}]
set_property src_info {type:XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M29        [get_ports {c2_ddr4_dm_n[5]}]
set_property src_info {type:XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J26        [get_ports {c2_ddr4_dm_n[6]}]
set_property src_info {type:XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C27        [get_ports {c2_ddr4_dm_n[7]}]
set_property src_info {type:XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E40        [get_ports {c2_ddr4_dm_n[8]}]
set_property src_info {type:XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R33        [get_ports {c2_ddr4_dq[0]}]
set_property src_info {type:XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P34        [get_ports {c2_ddr4_dq[10]}]
set_property src_info {type:XDC file:1 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P31        [get_ports {c2_ddr4_dq[11]}]
set_property src_info {type:XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N31        [get_ports {c2_ddr4_dq[12]}]
set_property src_info {type:XDC file:1 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R32        [get_ports {c2_ddr4_dq[13]}]
set_property src_info {type:XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N32        [get_ports {c2_ddr4_dq[14]}]
set_property src_info {type:XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R31        [get_ports {c2_ddr4_dq[15]}]
set_property src_info {type:XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K31        [get_ports {c2_ddr4_dq[16]}]
set_property src_info {type:XDC file:1 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K33        [get_ports {c2_ddr4_dq[17]}]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L32        [get_ports {c2_ddr4_dq[18]}]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M30        [get_ports {c2_ddr4_dq[19]}]
set_property src_info {type:XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T32        [get_ports {c2_ddr4_dq[1]}]
set_property src_info {type:XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L33        [get_ports {c2_ddr4_dq[20]}]
set_property src_info {type:XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J31        [get_ports {c2_ddr4_dq[21]}]
set_property src_info {type:XDC file:1 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K32        [get_ports {c2_ddr4_dq[22]}]
set_property src_info {type:XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L30        [get_ports {c2_ddr4_dq[23]}]
set_property src_info {type:XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H32        [get_ports {c2_ddr4_dq[24]}]
set_property src_info {type:XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G31        [get_ports {c2_ddr4_dq[25]}]
set_property src_info {type:XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G32        [get_ports {c2_ddr4_dq[26]}]
set_property src_info {type:XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H31        [get_ports {c2_ddr4_dq[27]}]
set_property src_info {type:XDC file:1 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E32        [get_ports {c2_ddr4_dq[28]}]
set_property src_info {type:XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F33        [get_ports {c2_ddr4_dq[29]}]
set_property src_info {type:XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T33        [get_ports {c2_ddr4_dq[2]}]
set_property src_info {type:XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F32        [get_ports {c2_ddr4_dq[30]}]
set_property src_info {type:XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E33        [get_ports {c2_ddr4_dq[31]}]
set_property src_info {type:XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R27        [get_ports {c2_ddr4_dq[32]}]
set_property src_info {type:XDC file:1 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P26        [get_ports {c2_ddr4_dq[33]}]
set_property src_info {type:XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T26        [get_ports {c2_ddr4_dq[34]}]
set_property src_info {type:XDC file:1 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N28        [get_ports {c2_ddr4_dq[35]}]
set_property src_info {type:XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T27        [get_ports {c2_ddr4_dq[36]}]
set_property src_info {type:XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P28        [get_ports {c2_ddr4_dq[37]}]
set_property src_info {type:XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N26        [get_ports {c2_ddr4_dq[38]}]
set_property src_info {type:XDC file:1 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R26        [get_ports {c2_ddr4_dq[39]}]
set_property src_info {type:XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U31        [get_ports {c2_ddr4_dq[3]}]
set_property src_info {type:XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L28        [get_ports {c2_ddr4_dq[40]}]
set_property src_info {type:XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K28        [get_ports {c2_ddr4_dq[41]}]
set_property src_info {type:XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J29        [get_ports {c2_ddr4_dq[42]}]
set_property src_info {type:XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L27        [get_ports {c2_ddr4_dq[43]}]
set_property src_info {type:XDC file:1 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H27        [get_ports {c2_ddr4_dq[44]}]
set_property src_info {type:XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H28        [get_ports {c2_ddr4_dq[45]}]
set_property src_info {type:XDC file:1 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M27        [get_ports {c2_ddr4_dq[46]}]
set_property src_info {type:XDC file:1 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J28        [get_ports {c2_ddr4_dq[47]}]
set_property src_info {type:XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F27        [get_ports {c2_ddr4_dq[48]}]
set_property src_info {type:XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G29        [get_ports {c2_ddr4_dq[49]}]
set_property src_info {type:XDC file:1 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T30        [get_ports {c2_ddr4_dq[4]}]
set_property src_info {type:XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D28        [get_ports {c2_ddr4_dq[50]}]
set_property src_info {type:XDC file:1 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E28        [get_ports {c2_ddr4_dq[51]}]
set_property src_info {type:XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E27        [get_ports {c2_ddr4_dq[52]}]
set_property src_info {type:XDC file:1 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H29        [get_ports {c2_ddr4_dq[53]}]
set_property src_info {type:XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26        [get_ports {c2_ddr4_dq[54]}]
set_property src_info {type:XDC file:1 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G27        [get_ports {c2_ddr4_dq[55]}]
set_property src_info {type:XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B30        [get_ports {c2_ddr4_dq[56]}]
set_property src_info {type:XDC file:1 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B29        [get_ports {c2_ddr4_dq[57]}]
set_property src_info {type:XDC file:1 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A29        [get_ports {c2_ddr4_dq[58]}]
set_property src_info {type:XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D29        [get_ports {c2_ddr4_dq[59]}]
set_property src_info {type:XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V31        [get_ports {c2_ddr4_dq[5]}]
set_property src_info {type:XDC file:1 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E30        [get_ports {c2_ddr4_dq[60]}]
set_property src_info {type:XDC file:1 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D30        [get_ports {c2_ddr4_dq[61]}]
set_property src_info {type:XDC file:1 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C29        [get_ports {c2_ddr4_dq[62]}]
set_property src_info {type:XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A30        [get_ports {c2_ddr4_dq[63]}]
set_property src_info {type:XDC file:1 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C38        [get_ports {c2_ddr4_dq[64]}]
set_property src_info {type:XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C39        [get_ports {c2_ddr4_dq[65]}]
set_property src_info {type:XDC file:1 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E38        [get_ports {c2_ddr4_dq[66]}]
set_property src_info {type:XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D38        [get_ports {c2_ddr4_dq[67]}]
set_property src_info {type:XDC file:1 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B40        [get_ports {c2_ddr4_dq[68]}]
set_property src_info {type:XDC file:1 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A40        [get_ports {c2_ddr4_dq[69]}]
set_property src_info {type:XDC file:1 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U32        [get_ports {c2_ddr4_dq[6]}]
set_property src_info {type:XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E39        [get_ports {c2_ddr4_dq[70]}]
set_property src_info {type:XDC file:1 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D39        [get_ports {c2_ddr4_dq[71]}]
set_property src_info {type:XDC file:1 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U30        [get_ports {c2_ddr4_dq[7]}]
set_property src_info {type:XDC file:1 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N34        [get_ports {c2_ddr4_dq[8]}]
set_property src_info {type:XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N33        [get_ports {c2_ddr4_dq[9]}]
set_property src_info {type:XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V32        [get_ports {c2_ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V33        [get_ports {c2_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:1 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M34        [get_ports {c2_ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L34        [get_ports {c2_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:1 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K30        [get_ports {c2_ddr4_dqs_t[2]}]
set_property src_info {type:XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J30        [get_ports {c2_ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J33        [get_ports {c2_ddr4_dqs_t[3]}]
set_property src_info {type:XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H33        [get_ports {c2_ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:1 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P29        [get_ports {c2_ddr4_dqs_t[4]}]
set_property src_info {type:XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N29        [get_ports {c2_ddr4_dqs_c[4]}]
set_property src_info {type:XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K26        [get_ports {c2_ddr4_dqs_t[5]}]
set_property src_info {type:XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K27        [get_ports {c2_ddr4_dqs_c[5]}]
set_property src_info {type:XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F28        [get_ports {c2_ddr4_dqs_t[6]}]
set_property src_info {type:XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F29        [get_ports {c2_ddr4_dqs_c[6]}]
set_property src_info {type:XDC file:1 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A27        [get_ports {c2_ddr4_dqs_t[7]}]
set_property src_info {type:XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A28        [get_ports {c2_ddr4_dqs_c[7]}]
set_property src_info {type:XDC file:1 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B39        [get_ports {c2_ddr4_dqs_t[8]}]
set_property src_info {type:XDC file:1 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A39        [get_ports {c2_ddr4_dqs_c[8]}]
set_property src_info {type:XDC file:1 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D40        [get_ports {c2_ddr4_odt[0]}]
set_property src_info {type:XDC file:1 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L29        [get_ports c2_ddr4_reset_n]
set_property src_info {type:XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19        [get_ports c3_ddr4_act_n]
set_property src_info {type:XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20        [get_ports {c3_ddr4_adr[0]}]
set_property src_info {type:XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19        [get_ports {c3_ddr4_adr[10]}]
set_property src_info {type:XDC file:1 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18        [get_ports {c3_ddr4_adr[11]}]
set_property src_info {type:XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19        [get_ports {c3_ddr4_adr[12]}]
set_property src_info {type:XDC file:1 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21        [get_ports {c3_ddr4_adr[13]}]
set_property src_info {type:XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20        [get_ports {c3_ddr4_adr[14]}]
set_property src_info {type:XDC file:1 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21        [get_ports {c3_ddr4_adr[15]}]
set_property src_info {type:XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18        [get_ports {c3_ddr4_adr[16]}]
set_property src_info {type:XDC file:1 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17        [get_ports {c3_ddr4_adr[1]}]
set_property src_info {type:XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18        [get_ports {c3_ddr4_adr[2]}]
set_property src_info {type:XDC file:1 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20        [get_ports {c3_ddr4_adr[3]}]
set_property src_info {type:XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18        [get_ports {c3_ddr4_adr[4]}]
set_property src_info {type:XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20        [get_ports {c3_ddr4_adr[5]}]
set_property src_info {type:XDC file:1 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21        [get_ports {c3_ddr4_adr[6]}]
set_property src_info {type:XDC file:1 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19        [get_ports {c3_ddr4_adr[7]}]
set_property src_info {type:XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19        [get_ports {c3_ddr4_adr[8]}]
set_property src_info {type:XDC file:1 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21        [get_ports {c3_ddr4_adr[9]}]
set_property src_info {type:XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20        [get_ports {c3_ddr4_ba[0]}]
set_property src_info {type:XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19        [get_ports {c3_ddr4_ba[1]}]
set_property src_info {type:XDC file:1 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20        [get_ports {c3_ddr4_bg[0]}]
set_property src_info {type:XDC file:1 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18        [get_ports {c3_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17        [get_ports {c3_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:1 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21        [get_ports {c3_ddr4_cke[0]}]
set_property src_info {type:XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N21        [get_ports {c3_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:1 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P13        [get_ports {c3_ddr4_dm_n[0]}]
set_property src_info {type:XDC file:1 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13        [get_ports {c3_ddr4_dm_n[1]}]
set_property src_info {type:XDC file:1 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14        [get_ports {c3_ddr4_dm_n[2]}]
set_property src_info {type:XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13        [get_ports {c3_ddr4_dm_n[3]}]
set_property src_info {type:XDC file:1 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21        [get_ports {c3_ddr4_dm_n[4]}]
set_property src_info {type:XDC file:1 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L25        [get_ports {c3_ddr4_dm_n[5]}]
set_property src_info {type:XDC file:1 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25        [get_ports {c3_ddr4_dm_n[6]}]
set_property src_info {type:XDC file:1 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22        [get_ports {c3_ddr4_dm_n[7]}]
set_property src_info {type:XDC file:1 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17        [get_ports {c3_ddr4_dm_n[8]}]
set_property src_info {type:XDC file:1 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14        [get_ports {c3_ddr4_dq[0]}]
set_property src_info {type:XDC file:1 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13        [get_ports {c3_ddr4_dq[10]}]
set_property src_info {type:XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14        [get_ports {c3_ddr4_dq[11]}]
set_property src_info {type:XDC file:1 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14        [get_ports {c3_ddr4_dq[12]}]
set_property src_info {type:XDC file:1 line:669 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15        [get_ports {c3_ddr4_dq[13]}]
set_property src_info {type:XDC file:1 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16        [get_ports {c3_ddr4_dq[14]}]
set_property src_info {type:XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16        [get_ports {c3_ddr4_dq[15]}]
set_property src_info {type:XDC file:1 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15        [get_ports {c3_ddr4_dq[16]}]
set_property src_info {type:XDC file:1 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16        [get_ports {c3_ddr4_dq[17]}]
set_property src_info {type:XDC file:1 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15        [get_ports {c3_ddr4_dq[18]}]
set_property src_info {type:XDC file:1 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13        [get_ports {c3_ddr4_dq[19]}]
set_property src_info {type:XDC file:1 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15        [get_ports {c3_ddr4_dq[1]}]
set_property src_info {type:XDC file:1 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16        [get_ports {c3_ddr4_dq[20]}]
set_property src_info {type:XDC file:1 line:678 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15        [get_ports {c3_ddr4_dq[21]}]
set_property src_info {type:XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15        [get_ports {c3_ddr4_dq[22]}]
set_property src_info {type:XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13        [get_ports {c3_ddr4_dq[23]}]
set_property src_info {type:XDC file:1 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14        [get_ports {c3_ddr4_dq[24]}]
set_property src_info {type:XDC file:1 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14        [get_ports {c3_ddr4_dq[25]}]
set_property src_info {type:XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13        [get_ports {c3_ddr4_dq[26]}]
set_property src_info {type:XDC file:1 line:684 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14        [get_ports {c3_ddr4_dq[27]}]
set_property src_info {type:XDC file:1 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16        [get_ports {c3_ddr4_dq[28]}]
set_property src_info {type:XDC file:1 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17        [get_ports {c3_ddr4_dq[29]}]
set_property src_info {type:XDC file:1 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14        [get_ports {c3_ddr4_dq[2]}]
set_property src_info {type:XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16        [get_ports {c3_ddr4_dq[30]}]
set_property src_info {type:XDC file:1 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17        [get_ports {c3_ddr4_dq[31]}]
set_property src_info {type:XDC file:1 line:690 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22        [get_ports {c3_ddr4_dq[32]}]
set_property src_info {type:XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R25        [get_ports {c3_ddr4_dq[33]}]
set_property src_info {type:XDC file:1 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P23        [get_ports {c3_ddr4_dq[34]}]
set_property src_info {type:XDC file:1 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24        [get_ports {c3_ddr4_dq[35]}]
set_property src_info {type:XDC file:1 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22        [get_ports {c3_ddr4_dq[36]}]
set_property src_info {type:XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M25        [get_ports {c3_ddr4_dq[37]}]
set_property src_info {type:XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P25        [get_ports {c3_ddr4_dq[38]}]
set_property src_info {type:XDC file:1 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N23        [get_ports {c3_ddr4_dq[39]}]
set_property src_info {type:XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14        [get_ports {c3_ddr4_dq[3]}]
set_property src_info {type:XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L22        [get_ports {c3_ddr4_dq[40]}]
set_property src_info {type:XDC file:1 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22        [get_ports {c3_ddr4_dq[41]}]
set_property src_info {type:XDC file:1 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24        [get_ports {c3_ddr4_dq[42]}]
set_property src_info {type:XDC file:1 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23        [get_ports {c3_ddr4_dq[43]}]
set_property src_info {type:XDC file:1 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J23        [get_ports {c3_ddr4_dq[44]}]
set_property src_info {type:XDC file:1 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H23        [get_ports {c3_ddr4_dq[45]}]
set_property src_info {type:XDC file:1 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L23        [get_ports {c3_ddr4_dq[46]}]
set_property src_info {type:XDC file:1 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J24        [get_ports {c3_ddr4_dq[47]}]
set_property src_info {type:XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D24        [get_ports {c3_ddr4_dq[48]}]
set_property src_info {type:XDC file:1 line:708 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22        [get_ports {c3_ddr4_dq[49]}]
set_property src_info {type:XDC file:1 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16        [get_ports {c3_ddr4_dq[4]}]
set_property src_info {type:XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25        [get_ports {c3_ddr4_dq[50]}]
set_property src_info {type:XDC file:1 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25        [get_ports {c3_ddr4_dq[51]}]
set_property src_info {type:XDC file:1 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23        [get_ports {c3_ddr4_dq[52]}]
set_property src_info {type:XDC file:1 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22        [get_ports {c3_ddr4_dq[53]}]
set_property src_info {type:XDC file:1 line:714 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F24        [get_ports {c3_ddr4_dq[54]}]
set_property src_info {type:XDC file:1 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23        [get_ports {c3_ddr4_dq[55]}]
set_property src_info {type:XDC file:1 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B25        [get_ports {c3_ddr4_dq[56]}]
set_property src_info {type:XDC file:1 line:717 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24        [get_ports {c3_ddr4_dq[57]}]
set_property src_info {type:XDC file:1 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24        [get_ports {c3_ddr4_dq[58]}]
set_property src_info {type:XDC file:1 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24        [get_ports {c3_ddr4_dq[59]}]
set_property src_info {type:XDC file:1 line:720 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14        [get_ports {c3_ddr4_dq[5]}]
set_property src_info {type:XDC file:1 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C26        [get_ports {c3_ddr4_dq[60]}]
set_property src_info {type:XDC file:1 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26        [get_ports {c3_ddr4_dq[61]}]
set_property src_info {type:XDC file:1 line:723 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C23        [get_ports {c3_ddr4_dq[62]}]
set_property src_info {type:XDC file:1 line:724 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25        [get_ports {c3_ddr4_dq[63]}]
set_property src_info {type:XDC file:1 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20        [get_ports {c3_ddr4_dq[64]}]
set_property src_info {type:XDC file:1 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19        [get_ports {c3_ddr4_dq[65]}]
set_property src_info {type:XDC file:1 line:727 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18        [get_ports {c3_ddr4_dq[66]}]
set_property src_info {type:XDC file:1 line:728 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18        [get_ports {c3_ddr4_dq[67]}]
set_property src_info {type:XDC file:1 line:729 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20        [get_ports {c3_ddr4_dq[68]}]
set_property src_info {type:XDC file:1 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20        [get_ports {c3_ddr4_dq[69]}]
set_property src_info {type:XDC file:1 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R15        [get_ports {c3_ddr4_dq[6]}]
set_property src_info {type:XDC file:1 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19        [get_ports {c3_ddr4_dq[70]}]
set_property src_info {type:XDC file:1 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18        [get_ports {c3_ddr4_dq[71]}]
set_property src_info {type:XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16        [get_ports {c3_ddr4_dq[7]}]
set_property src_info {type:XDC file:1 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13        [get_ports {c3_ddr4_dq[8]}]
set_property src_info {type:XDC file:1 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15        [get_ports {c3_ddr4_dq[9]}]
set_property src_info {type:XDC file:1 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16        [get_ports {c3_ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:1 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16        [get_ports {c3_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17        [get_ports {c3_ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16        [get_ports {c3_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:1 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17        [get_ports {c3_ddr4_dqs_t[2]}]
set_property src_info {type:XDC file:1 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16        [get_ports {c3_ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:1 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15        [get_ports {c3_ddr4_dqs_t[3]}]
set_property src_info {type:XDC file:1 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15        [get_ports {c3_ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P24        [get_ports {c3_ddr4_dqs_t[4]}]
set_property src_info {type:XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N24        [get_ports {c3_ddr4_dqs_c[4]}]
set_property src_info {type:XDC file:1 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K25        [get_ports {c3_ddr4_dqs_t[5]}]
set_property src_info {type:XDC file:1 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J25        [get_ports {c3_ddr4_dqs_c[5]}]
set_property src_info {type:XDC file:1 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23        [get_ports {c3_ddr4_dqs_t[6]}]
set_property src_info {type:XDC file:1 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22        [get_ports {c3_ddr4_dqs_c[6]}]
set_property src_info {type:XDC file:1 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A23        [get_ports {c3_ddr4_dqs_t[7]}]
set_property src_info {type:XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22        [get_ports {c3_ddr4_dqs_c[7]}]
set_property src_info {type:XDC file:1 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21        [get_ports {c3_ddr4_dqs_t[8]}]
set_property src_info {type:XDC file:1 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H21        [get_ports {c3_ddr4_dqs_c[8]}]
set_property src_info {type:XDC file:1 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17        [get_ports {c3_ddr4_odt[0]}]
set_property src_info {type:XDC file:1 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L24        [get_ports c3_ddr4_reset_n]
