# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/xcl_design_ddrmem_3_0.xci
# IP: The module: 'xcl_design_ddrmem_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_0/xcl_design_ddrmem_3_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs}]

# Block Designs: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/bd_c613.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613 || ORIG_REF_NAME==bd_c613}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_microblaze_I_0 || ORIG_REF_NAME==bd_c613_microblaze_I_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_rst_0_0 || ORIG_REF_NAME==bd_c613_rst_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_2/bd_c613_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_ilmb_0 || ORIG_REF_NAME==bd_c613_ilmb_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_3/bd_c613_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_dlmb_0 || ORIG_REF_NAME==bd_c613_dlmb_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_4/bd_c613_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c613_dlmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_5/bd_c613_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c613_ilmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_6/bd_c613_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_lmb_bram_I_0 || ORIG_REF_NAME==bd_c613_lmb_bram_I_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_7/bd_c613_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c613_second_dlmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_8/bd_c613_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c613_second_ilmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_9/bd_c613_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_c613_second_lmb_bram_I_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_10/bd_c613_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_iomodule_0_0 || ORIG_REF_NAME==bd_c613_iomodule_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_1/xcl_design_ddrmem_3_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0_phy || ORIG_REF_NAME==xcl_design_ddrmem_3_0_phy}]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_microblaze_I_0 || ORIG_REF_NAME==bd_c613_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_rst_0_0 || ORIG_REF_NAME==bd_c613_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_rst_0_0 || ORIG_REF_NAME==bd_c613_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_2/bd_c613_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_ilmb_0 || ORIG_REF_NAME==bd_c613_ilmb_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_2/bd_c613_ilmb_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_3/bd_c613_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_dlmb_0 || ORIG_REF_NAME==bd_c613_dlmb_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_3/bd_c613_dlmb_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_4/bd_c613_dlmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_5/bd_c613_ilmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_6/bd_c613_lmb_bram_I_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_7/bd_c613_second_dlmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_8/bd_c613_second_ilmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_9/bd_c613_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_10/bd_c613_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_iomodule_0_0 || ORIG_REF_NAME==bd_c613_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_10/bd_c613_iomodule_0_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/bd_c613_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_0/xcl_design_ddrmem_3_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs}] {/inst }]/inst ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_0/xcl_design_ddrmem_3_0_microblaze_mcs_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_1/par/xcl_design_ddrmem_3_0_phy_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/xcl_design_ddrmem_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/par/xcl_design_ddrmem_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/xcl_design_ddrmem_3_0.xci
# IP: The module: 'xcl_design_ddrmem_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_0/xcl_design_ddrmem_3_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs}]

# Block Designs: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/bd_c613.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613 || ORIG_REF_NAME==bd_c613}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_microblaze_I_0 || ORIG_REF_NAME==bd_c613_microblaze_I_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_rst_0_0 || ORIG_REF_NAME==bd_c613_rst_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_2/bd_c613_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_ilmb_0 || ORIG_REF_NAME==bd_c613_ilmb_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_3/bd_c613_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_dlmb_0 || ORIG_REF_NAME==bd_c613_dlmb_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_4/bd_c613_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c613_dlmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_5/bd_c613_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c613_ilmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_6/bd_c613_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_lmb_bram_I_0 || ORIG_REF_NAME==bd_c613_lmb_bram_I_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_7/bd_c613_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c613_second_dlmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_8/bd_c613_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c613_second_ilmb_cntlr_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_9/bd_c613_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_c613_second_lmb_bram_I_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_10/bd_c613_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c613_iomodule_0_0 || ORIG_REF_NAME==bd_c613_iomodule_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_1/xcl_design_ddrmem_3_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0_phy || ORIG_REF_NAME==xcl_design_ddrmem_3_0_phy}]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_microblaze_I_0 || ORIG_REF_NAME==bd_c613_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_0/bd_c613_microblaze_I_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_rst_0_0 || ORIG_REF_NAME==bd_c613_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_rst_0_0 || ORIG_REF_NAME==bd_c613_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_1/bd_c613_rst_0_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_2/bd_c613_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_ilmb_0 || ORIG_REF_NAME==bd_c613_ilmb_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_2/bd_c613_ilmb_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_3/bd_c613_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_dlmb_0 || ORIG_REF_NAME==bd_c613_dlmb_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_3/bd_c613_dlmb_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_4/bd_c613_dlmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_5/bd_c613_ilmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_6/bd_c613_lmb_bram_I_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_7/bd_c613_second_dlmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_8/bd_c613_second_ilmb_cntlr_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_9/bd_c613_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_10/bd_c613_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c613_iomodule_0_0 || ORIG_REF_NAME==bd_c613_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/ip/ip_10/bd_c613_iomodule_0_0_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/bd_0/bd_c613_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_0/xcl_design_ddrmem_3_0_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_3_0_microblaze_mcs}] {/inst }]/inst ]]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_0/xcl_design_ddrmem_3_0_microblaze_mcs_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/ip_1/par/xcl_design_ddrmem_3_0_phy_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/xcl_design_ddrmem_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_3_0/par/xcl_design_ddrmem_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
