# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_9/bd_2fd7_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2fd7_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_9/bd_2fd7_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2fd7_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
