# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0.xci
# IP: The module: 'xcl_design_psreset_gate_pr_kernel_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_gate_pr_kernel_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_gate_pr_kernel_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_gate_pr_kernel_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0.xci
# IP: The module: 'xcl_design_psreset_gate_pr_kernel_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_gate_pr_kernel_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_gate_pr_kernel_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_gate_pr_kernel_0/xcl_design_psreset_gate_pr_kernel_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_gate_pr_kernel_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
