# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0.xci
# IP: The module: 'xcl_design_u_ocl_region_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7 || ORIG_REF_NAME==bd_2fd7}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_0/bd_2fd7_m_axi_interconnect_M00_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_2/bd_2fd7_m_axi_interconnect_M01_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_4/bd_2fd7_m_axi_interconnect_M02_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M02_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M02_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_6/bd_2fd7_m_axi_interconnect_M03_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M03_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M03_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_8/bd_2fd7_s_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s_axi_interconnect_0_0 || ORIG_REF_NAME==bd_2fd7_s_axi_interconnect_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_9/bd_2fd7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_xbar_0 || ORIG_REF_NAME==bd_2fd7_xbar_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_14/bd_2fd7_data_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_data_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_data_sys_reset_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_15/bd_2fd7_control_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_control_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_control_sys_reset_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_16/bd_2fd7_kernel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_0_0 || ORIG_REF_NAME==bd_2fd7_kernel_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_17/bd_2fd7_kernel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_1_0 || ORIG_REF_NAME==bd_2fd7_kernel_1_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_18/bd_2fd7_kernel_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_2_0 || ORIG_REF_NAME==bd_2fd7_kernel_2_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_19/bd_2fd7_kernel_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_3_0 || ORIG_REF_NAME==bd_2fd7_kernel_3_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_20/bd_2fd7_slave_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_slave_bridge_0 || ORIG_REF_NAME==bd_2fd7_slave_bridge_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_21/bd_2fd7_master_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_0_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_22/bd_2fd7_master_bridge_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_1_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_1_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_23/bd_2fd7_master_bridge_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_2_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_2_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_24/bd_2fd7_master_bridge_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_3_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_3_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_1/bd_2fd7_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_0 || ORIG_REF_NAME==bd_2fd7_s00_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_3/bd_2fd7_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_1 || ORIG_REF_NAME==bd_2fd7_s00_regslice_1}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_5/bd_2fd7_s00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_2 || ORIG_REF_NAME==bd_2fd7_s00_regslice_2}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_7/bd_2fd7_s00_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_3 || ORIG_REF_NAME==bd_2fd7_s00_regslice_3}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_10/bd_2fd7_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m00_regslice_0 || ORIG_REF_NAME==bd_2fd7_m00_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_11/bd_2fd7_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m01_regslice_0 || ORIG_REF_NAME==bd_2fd7_m01_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_12/bd_2fd7_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m02_regslice_0 || ORIG_REF_NAME==bd_2fd7_m02_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_13/bd_2fd7_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m03_regslice_0 || ORIG_REF_NAME==bd_2fd7_m03_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_25/bd_2fd7_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_0 || ORIG_REF_NAME==bd_2fd7_auto_cc_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_26/bd_2fd7_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_1 || ORIG_REF_NAME==bd_2fd7_auto_cc_1}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_27/bd_2fd7_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_2 || ORIG_REF_NAME==bd_2fd7_auto_cc_2}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_28/bd_2fd7_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_3 || ORIG_REF_NAME==bd_2fd7_auto_cc_3}]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_u_ocl_region_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0.xci
# IP: The module: 'xcl_design_u_ocl_region_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7 || ORIG_REF_NAME==bd_2fd7}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_0/bd_2fd7_m_axi_interconnect_M00_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_2/bd_2fd7_m_axi_interconnect_M01_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_4/bd_2fd7_m_axi_interconnect_M02_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M02_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M02_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_6/bd_2fd7_m_axi_interconnect_M03_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M03_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M03_AXI_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_8/bd_2fd7_s_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s_axi_interconnect_0_0 || ORIG_REF_NAME==bd_2fd7_s_axi_interconnect_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_9/bd_2fd7_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_xbar_0 || ORIG_REF_NAME==bd_2fd7_xbar_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_14/bd_2fd7_data_sys_reset_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_data_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_data_sys_reset_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_15/bd_2fd7_control_sys_reset_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_control_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_control_sys_reset_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_16/bd_2fd7_kernel_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_0_0 || ORIG_REF_NAME==bd_2fd7_kernel_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_17/bd_2fd7_kernel_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_1_0 || ORIG_REF_NAME==bd_2fd7_kernel_1_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_18/bd_2fd7_kernel_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_2_0 || ORIG_REF_NAME==bd_2fd7_kernel_2_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_19/bd_2fd7_kernel_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_3_0 || ORIG_REF_NAME==bd_2fd7_kernel_3_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_20/bd_2fd7_slave_bridge_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_slave_bridge_0 || ORIG_REF_NAME==bd_2fd7_slave_bridge_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_21/bd_2fd7_master_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_0_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_0_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_22/bd_2fd7_master_bridge_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_1_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_1_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_23/bd_2fd7_master_bridge_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_2_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_2_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_24/bd_2fd7_master_bridge_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_3_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_3_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_1/bd_2fd7_s00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_0 || ORIG_REF_NAME==bd_2fd7_s00_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_3/bd_2fd7_s00_regslice_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_1 || ORIG_REF_NAME==bd_2fd7_s00_regslice_1}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_5/bd_2fd7_s00_regslice_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_2 || ORIG_REF_NAME==bd_2fd7_s00_regslice_2}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_7/bd_2fd7_s00_regslice_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_3 || ORIG_REF_NAME==bd_2fd7_s00_regslice_3}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_10/bd_2fd7_m00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m00_regslice_0 || ORIG_REF_NAME==bd_2fd7_m00_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_11/bd_2fd7_m01_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m01_regslice_0 || ORIG_REF_NAME==bd_2fd7_m01_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_12/bd_2fd7_m02_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m02_regslice_0 || ORIG_REF_NAME==bd_2fd7_m02_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_13/bd_2fd7_m03_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m03_regslice_0 || ORIG_REF_NAME==bd_2fd7_m03_regslice_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_25/bd_2fd7_auto_cc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_0 || ORIG_REF_NAME==bd_2fd7_auto_cc_0}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_26/bd_2fd7_auto_cc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_1 || ORIG_REF_NAME==bd_2fd7_auto_cc_1}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_27/bd_2fd7_auto_cc_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_2 || ORIG_REF_NAME==bd_2fd7_auto_cc_2}]

# IP: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_28/bd_2fd7_auto_cc_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_3 || ORIG_REF_NAME==bd_2fd7_auto_cc_3}]

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7_ooc.xdc

# XDC: c:/Sim/sdaccel_ku/xcl_design/xcl_design.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_u_ocl_region_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
